name: deploy-slsm

on: 
 push: 
  tags: 
  - SLSM/v*
env: 
	ProjectPath: D:/WPF/SLSM/SLSM.csproj
jobs:
	deploy:
		runs-on: windows-latest
		steps: 
			-uses: actions/checkout@v2
			-uses: actions/setup-dotnet@v1
			 with:
				dotnet-version: 8.1.x
			-run: dotnet restore ${{env.ProjectPath}}
			-run: dotnet build ${{env.ProjectPath}} -c Release --no-restore
			-run: dotnet publish ${{env.ProjectPath}} -c Release --self-contained -r win-x64 -p:PublishSingleFile=True --no-build
			-uses: actions/create-release@v1
			   id: create_release
			  env: 
				GithubToken: ${{secrets.GithubToken}}
			 with:
				tag_name: ${{github.ref}}
				release_name: ${{github.ref}}
			-uses: csexton/release-asset-action@v2
			 with: 
				github-token: ${{secrets.GithubToken}}
				pattern: 
				- D:/WPF/SLSM/bin/Release/net8.0-windows/win-x64/publish/*exe
				release-url: ${{steps.create_release.outputs.upload_url}}
				
					


